[2023-01-05 06:06:45] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:45] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:46] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:47] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:47] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:48] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:48] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:48] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:49] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:49] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:49] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:50] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:50] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:50] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:50] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:51] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:52] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:52] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:52] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:53] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:53] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:53] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:54] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:54] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:54] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:55] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:55] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
[2023-01-05 06:06:55] local.ERROR: Cannot use App\Http\Controllers\Frontend\TrackingController as TrackingController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\Frontend\\TrackingController as TrackingController because the name is already in use at /Applications/XAMPP/xamppfiles/htdocs/Sky_Track/skytracker/routes/frontend/home.php:9)
[stacktrace]
#0 {main}
"} 
